### ISSUE TITLE
Controlled <ListBox />  3.0 breaks when using keyboard

### ISSUE THREAD

**Issue by allison-c** [acl-services/paprika#1024]
# Bug Report

Go to https://codesandbox.io/s/romantic-moore-40x30?file=/src/App.js
- click the trigger
- use keyboard to select an item

## Expected behavior

should work

## Current behavior

app breaks

## Screenshots / Gifs / Codepens

https://codesandbox.io/s/romantic-moore-40x30?file=/src/App.js

## Additional context

When the options re-renders, they generate new ids, but the ids in the outside context didn't change, so the app breaks

**Comment by nahumzs** [comment]
This has been fixed on UXD-1134 🙏, let me know if you keep having problems after updating the package @allison-c
