### ISSUE TITLE
Using ListBox.Box in TS makes children required

### ISSUE THREAD

**Issue by Nandez89** [acl-services/paprika#1040]
# Bug Report
## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a bug report.
- [x] I checked to make sure that this bug has not already been filed
- [x] I reproduced the bug in the latest version of paprika
- [x] Please label as, low / medium / high priority

*Please fill in as much detail as possible below*
When using the `ListBox.Box` as shown in the examples in _Subcomponents.js_ to give the `Box` a custom class. TS complains that children are required. However, the examples show using the `ListBox.Box` as a self-closing tag. Using it as a wrapper for options breaks the component

## Expected behavior
Either make the children prop more flexible for typescript to not complain or adjust its behavior so it can be used as a wrapper around the options instead

## Current behavior
TS errors due to ListBox.Box requiring a children prop and `ts-ignore` is required

## Screenshots / Gifs / Codepens
![Screen Shot 2021-05-11 at 2 03 31 PM](https://user-images.githubusercontent.com/1757057/117885700-00365800-b263-11eb-9b0b-5f06ccd537cc.png)

Example Story:
![Screen Shot 2021-05-11 at 2 11 42 PM](https://user-images.githubusercontent.com/1757057/117885724-09272980-b263-11eb-87a6-cce84333d64a.png)

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by leonatgalvanize** [comment]
Resolved with #1099
