### ISSUE TITLE
Collapsible arrow icon should be vertically aligned

### ISSUE THREAD

**Issue by oscarkwan** [acl-services/paprika#121]
# Bug Report
## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a bug report.
- [x] I checked to make sure that this bug has not already been filed
- [x] I reproduced the bug in the latest version of paprika
- [x] Please label as, low / medium / high priority

*Please fill in as much detail as possible below*

## Expected behavior
*Please describe the behavior you are expecting to happen.*
The arrow icon should be aligned vertically with the text. 

![Screen Shot 2019-07-12 at 2 33 02 PM](https://user-images.githubusercontent.com/19940076/61160233-8fca1e80-a4b3-11e9-94cc-232ff0f17aae.png)

## Current behavior
*What is the current behavior?*
The arrow icon is not aligned vertically with the text.
Right now there is more padding below than on top.

![Screen Shot 2019-07-12 at 2 31 18 PM](https://user-images.githubusercontent.com/19940076/61160216-82149900-a4b3-11e9-8351-b56ad89ead88.png)

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*
- images above

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by mikrotron** [comment]
Coming soon!
https://github.com/acl-services/paprika/pull/125/files#diff-6d20323cb4f2c7b29ce7c19e70700239R23
