### ISSUE TITLE
Popover – follow-up issues

### ISSUE THREAD

**Issue by mikrotron** [acl-services/paprika#127]
#### Problem
`<Popover.Tip>` does not utilize the `zIndex` prop on the `<Popover>` root element, and so inconveniently requires its own `zIndex` prop to display on the same level as the rest of the Popover content.

#### Suggested Solution
If no `zIndex` is specifically provided to the `<Popover.Tip>`, then it should use the `zIndex` prop from `context`.

---

#### ~Problem~
~Sometimes a layout change is applied to the view without re-rendering the Popover, and so the `<Popover.Trigger>` position may move, but if the Popover is open, its content is not repositioned.~

#### ~Suggested Solution~
~Introduce an imperative API method – something like `reposition()` that can be called on the `<Popover>` by a controlling component that is aware of the (potential) view change.~

Re-opened as: https://github.com/acl-services/paprika/issues/240

**Comment by alexzherdev** [comment]
I'd be curious to see an example of the second issue; perhaps we could avoid an imperative API. Additionally, if something like that is needed, maybe a `forceUpdate()` would be enough?

**Comment by tristanjasper** [comment]
New Popover Issue to add to this:

**Problem**
Popover Content alignment is not correctly aligned to the trigger element when rendering the trigger in different positions. This is affecting the dropdown component as well as the datepicker.

![image](https://user-images.githubusercontent.com/4040102/61498124-e2ee1680-a976-11e9-8c27-39275c1943d1.png)
![image](https://user-images.githubusercontent.com/4040102/61498136-eda8ab80-a976-11e9-8581-425053961d0d.png)

**Suggested solution**
Allow an additional prop of "isContentAlignedToTrigger" perhaps to restrict its position

**Comment by tristanjasper** [comment]
**Problem**
When there is no children rendered in the <Popover.Content> component there is still an 18px gap being rendered. Perhaps due to positioning. This is a a problem for the Paprika Dropdown Component as it shows a gab to a second Popover.
![image](https://user-images.githubusercontent.com/4040102/61498424-0e253580-a978-11e9-9184-2d685287852a.png)

**Suggested solution**
Unsure at this time

**Comment by nahumzs** [comment]
@mikrotron are all these issues fixed on UX-548? can we close this issue?

**Comment by mikrotron** [comment]
2/4 are fixed.  
1/4 is maybe not needed... what do you think? (https://github.com/acl-services/paprika/issues/127#issuecomment-512510035)
The remaining issue (alignment) can be moved out to a new issue, so we can close this one.

**Comment by mikrotron** [comment]
Issue created: https://github.com/acl-services/paprika/issues/182

**Comment by mikrotron** [comment]
3/4 are resolved, and the remaining one has been re-opened as https://github.com/acl-services/paprika/issues/240
