### ISSUE TITLE
Not show focus styling if user is not using a keyboard

### ISSUE THREAD

**Issue by oscarkwan** [acl-services/paprika#172]
# Feature request
## Prerequisites
Going to relay a message here from @mattcrest  on focus styling.

Basically, we don’t want focus styling to appear if we are *not* using the keyboard to navigate through our components. 

We would want this as a global change so for all our components this won't happen.

## Is your feature request related to a problem?
- We don't want focus styling to appear if you are not using the keyboard to interact

## Describe the solution you'd like
- a Global change that will affect all components going forward

![Screen Shot 2019-08-20 at 1 42 48 PM](https://user-images.githubusercontent.com/19940076/63386067-1564a800-c357-11e9-9a76-75ea6835b3ae.png)

**Comment by oscarkwan** [comment]
I don't have a solution in mind at the moment, open to discussion

**Comment by jamiek-acl** [comment]
How about a listener that adds a class to the body when the keyboard is used, and removes that class when the mouse is clicked?
Then in that class remove the focus style.

**Comment by oscarkwan** [comment]
> How about a listener that adds a class to the body when the keyboard is used, and removes that class when the mouse is clicked?
> Then in that class remove the focus style.

🤔 🤔 Good suggestion

**Comment by alexzherdev** [comment]
[:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) would be the proper solution, but browser support is still limited 😕 
https://stackoverflow.com/a/51093815 has a couple code samples, looks like @jamiek-acl's idea might work. Although I'm not a fan of the library operating on such a global level, but ‾\\\_(ツ)_/‾

**Comment by mikrotron** [comment]
We adopted Jamie's approach for the _almost dead_ Starling site.  I don't think it creates any major issues, but I also have the same knee-jerk reservations about a global script.  It's also not so easy to remove, because it means we have to add a lot of conditions throughout the css of our components.

**Comment by mikrotron** [comment]
The library used on the Starling site:
https://github.com/ten1seven/what-input

**Comment by nahumzs** [comment]
some examples implementing @jamiek-acl ideas https://jmperezperez.com/outline-focus-ring-a11y/ https://medium.com/hackernoon/removing-that-ugly-focus-ring-and-keeping-it-too-6c8727fefcd2

seems like the way to go.

**Comment by mikrotron** [comment]
Resolved by https://github.com/acl-services/paprika/pull/373
