### ISSUE TITLE
Date picker integration bugs

### ISSUE THREAD

**Issue by allison-c** [acl-services/paprika#174]
# Bug Report
## Expected behavior
Date picker should not be blinking.
Date input should work correctly.

## Current behavior
Date picker is blinking before close.
Cannot type in the date input.

## Screenshots / Gifs / Codepens
Created an example, trying to reproduce the typing issue. https://codesandbox.io/s/unruffled-hellman-o9kyf

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by nahumzs** [comment]
can you extend the explanation about cannot type in the date input?

**Comment by tristanjasper** [comment]
Believe this to now be addressed via tickets
https://github.com/acl-services/paprika/pull/204
https://github.com/acl-services/paprika/pull/207
Will close this issue @allison-c

**Comment by allison-c** [comment]
Fixed in https://github.com/acl-services/paprika/pull/200
