### ISSUE TITLE
DropdownMenu – Add support for an anchor attribute to identify Popover portal content

### ISSUE THREAD

**Issue by mikrotron** [acl-services/paprika#183]
## Problem
Since the menu content of the `<DropdownMenu>` is rendered in a portal, when there are multiple `<DropdownMenus>` on a page, there will be no unique identifier in the markup to target it with automation tests, CSS overrides or scripts.  

The `<Popover.Content>` does propagate additional props, so a `data-testid` attribute _can_ be included on the portal DOM element, but the current API for the `<DropdownMenu>` does not expose access to its internal `<Popover.Content>` element.  

Simply adding a `data-pka-anchor='dropdown-menu.popover-content'` will be insufficient, since all DropdownMenu portals would share the same attribute.  Additionally, Paprika components have thus far remained agnostic about testing attribute names, so naming a prop is a challenge.

## Suggested Solution

Since it may be convenient to capture and propagate various props for both the `<Popover>` and `<Popover.Content>` that are implemented in the `<DropdownMenu>`, a similar pattern that is used in the `<DataPicker>` and `<ListBox>` could be employed to extract props from a "container" component. 

In fact the `extractChildrenProps()` helper could be extracted from `<DatePicker>` to the `Helpers` package to be shared:

https://github.com/acl-services/paprika/blob/master/packages/DatePicker/src/helpers.js#L4-L14

The resulting API would look like:
```jsx
<DropdownMenu>
  <DropdownMenu.Content data-testid="special-menu" />
  <DropdownMenu.Item>Menu item</DropdownMenu.Item>
  ...
</DropdownMenu>
```

**Comment by mikrotron** [comment]
This issue now applies to the `<Confirmation>` component as well.

_However_, since only ONE `<Popover>` should ever be visible (rendered) at a time, a workaround is to simply locate the only `[data-pka-anchor='popover.content']` element on the page.

**Comment by jamiek-acl** [comment]
Donezo.
https://github.com/acl-services/paprika/pull/1002
