### ISSUE TITLE
ListBox.Divider without text.

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#191]
Currently `ListBox.Divider` force the developer to provide a text, though there are legit cases when the divider doesn't require a description. 

> I notice when I don’t put anything like <ListBox.Divider />, I got an error because children are required
And when the divider renders, there is a space in the middle.

## Expected behaviour.

If `<ListBox.Divider />` is provided without text should render just a horizontal line.

**Comment by allison-c** [comment]
Reopen this issue since it's not supported anymore https://codesandbox.io/s/eloquent-yalow-ohll0?file=/src/App.js

**Comment by nahumzs** [comment]
This has been solved.

**Comment by nahumzs** [comment]
https://codesandbox.io/s/listbox-divider-no-text-fhipc?file=/src/App.js
