### ISSUE TITLE
Add analytics to track usage (Google Analytics or Pendo)

### ISSUE THREAD

**Issue by pxsmith** [acl-services/paprika#211]
# Feature request
**Problem**
Knowing which stories are most popular will help us ensure an excellent developer experience. Right now, we have no idea which pages are used.

**Solution**
Add tracking to a Google Analytics account ([here’s how](https://github.com/storybookjs/storybook/tree/master/addons/google-analytics)) and/or to our Pendo account.

**Comment by nahumzs** [comment]
We already have our internal sonar app that take care of this,
