### ISSUE TITLE
DatePicker Issues/Suggestions

### ISSUE THREAD

**Issue by tristanjasper** [acl-services/paprika#217]
# Feature request
## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a feature request.
- [ ] I checked to make sure that this feature has not already been suggested
- [ ] Please label as, low / medium / high priority

*Please fill in as much detail as possible*

## Is your feature request related to a problem?

1. Expand the DatePicker unit tests (`DatePicker.spec.js` ) to include an array of contexts containing various country details and use moment to set the timezone in different `it` blocks

`moment.tz.setDefault(String)`

2. Date Picker errors should be expanded to additionally send an error event if there is an empty string set. This is so that the consuming application could show the correct error (for example if the date is required) ie "This field cannot be blank".

## Describe the solution you'd like
*A clear and concise description of what you want to happen.*

## Describe alternatives you've considered
*A clear and concise description of any alternative solutions or features you've considered.*

## Additional context
*Add any other context or screenshots about the feature request here.*

**Comment by oscarkwan** [comment]
Stale issue. Closing.
