### ISSUE TITLE
Sortable a11y

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#222]
# Bug Report
1. The sortable component does not pass a11y (colour contrast of the sort order number).

<img width="546" alt="Screen Shot 2019-10-09 at 9 14 42 AM" src="https://user-images.githubusercontent.com/23224777/66499859-76fee400-ea75-11e9-9791-25a2d70e1b39.png">

2. Also while in here, enlarge the size of the trashbin icon so it is 18px.

**Comment by krismckinnonacl** [comment]
I'd like to update this to match the same values as the pill component already built in ACL-UI, which is an existing colour combination for text on a grey background. Here is an example (I'll update the invision mockups as well. 
<img width="557" alt="Screen Shot 2019-10-09 at 9 35 26 AM" src="https://user-images.githubusercontent.com/20196567/66501684-ae22c480-ea78-11e9-8499-c5f6fd22b6a1.png">

**Comment by tristanjasper** [comment]
I have enlarged the trash can button icon in a separate PR - https://github.com/acl-services/paprika/pull/229
