### ISSUE TITLE
SVGR generated id will be repeated if we use multiple same icon on one page

### ISSUE THREAD

**Issue by allison-c** [acl-services/paprika#224]
# Bug Report
## Prerequisites
Icon component generated by SVGR:
```javascript
import React from "react";

const SvgAdd = ({ title, ...props }) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    css={`
      color: ${props.color};
      width: ${props.size};
      height: ${props.size};
      vertical-align: text-top;
    `}
    focusable={false}
    {...props}
  >
    <title>{title}</title>
    <defs>
      <path
        d="M1.5 10.425h7.875a1.05 1.05 0 0 0 1.05-1.05V1.5h3.15v7.875a1.05 1.05 0 0 0 1.05 1.05H22.5v3.15h-7.875a1.05 1.05 0 0 0-1.05 1.05V22.5h-3.15v-7.875a1.05 1.05 0 0 0-1.05-1.05H1.5v-3.15z"
        id="add_svg__a"
      />
    </defs>
    <use fill="currentColor" xlinkHref="#add_svg__a" fillRule="evenodd" />
  </svg>
);

export default SvgAdd;

```
As you can see the id `add_svg__a` is generated. If there's more than one plus icon on the page, it will introduce repeated id issue.

## Expected behavior
*Please describe the behavior you are expecting to happen.*

## Current behavior
*What is the current behavior?*

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by nahumzs** [comment]
@allison-c can you close this one if you solved this issue in the previous PR?

**Comment by allison-c** [comment]
Fixed by https://github.com/acl-services/paprika/pull/405
