### ISSUE TITLE
Ensure all react peer dependencies are at least set to `^16.8.0` 

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#225]
# Bug Report

Ensure all react peer dependencies are at least set to `^16.8.0`, there are several package.json which are set below the hooks release. 

Solution: 

```json
    "react": "^16.8.0",
    "react-dom": "^16.8.0",
```
--- 

Some packages with peerdendecy less than 16.8.0 :

https://github.com/acl-services/paprika/blob/1e13e22889724b7e629fac2fed7d7f534aa93f66/packages/Icon/package.json

https://github.com/acl-services/paprika/blob/1e13e22889724b7e629fac2fed7d7f534aa93f66/packages/Icon/package.json

https://github.com/acl-services/paprika/blob/cd908fc16fe7b06b6a6f5a2ad0e39a6e50a2ab8a/packages/Heading/package.json

https://github.com/acl-services/paprika/blob/320525ad89d162a636041b7a54071b6ee18b99a5/packages/RawButton/package.json

https://github.com/acl-services/paprika/blob/bc155f4690be5e6d4bc319ff6e236c430f8b0065/packages/Spinner/package.json

https://github.com/acl-services/paprika/blob/bc155f4690be5e6d4bc319ff6e236c430f8b0065/packages/Input/package.json

https://github.com/acl-services/paprika/blob/bb7c55038f274bce52f9fa9615775c34f9f631e6/packages/Popover/package.json

and more ...

**Comment by sowmiyamuthuraman** [comment]
can I work on this?

**Comment by nahumzs** [comment]
We should also check that all our components have ReactDom as a peer dependency as well.

**Comment by AndreyChernykh** [comment]
https://github.com/acl-services/paprika/pull/234

**Comment by nahumzs** [comment]
resolve by #234
