### ISSUE TITLE
Cleanup PropType usage strings to variables

### ISSUE THREAD

**Issue by tristanjasper** [acl-services/paprika#228]
# Bug Report
## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a bug report.
- [x] I checked to make sure that this bug has not already been filed
- [ ] I reproduced the bug in the latest version of paprika
- [ ] Please label as, low / medium / high priority

Currently i'm seeing many single strings throughout our components, relating to sizes and button types. 

This Pr updates the components to use a variable

## Expected behavior
*Please describe the behavior you are expecting to happen.*

## Current behavior
*What is the current behavior?*

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by oscarkwan** [comment]
Stale issue. Closing.
