### ISSUE TITLE
Changelogs for every Paprika component

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#238]
We need a proper way to communicate the changelog for our components, right now we don't have a process on places. 

This will help developers to migrate to a new version easily and with confidence. 

Some inspiration:
https://twitter.com/mjackson/status/1179518588488540163

**Comment by jamiek-acl** [comment]
Hey @nahumzs , can this ticket be closed? We are creating changelogs for our components now with `changeset`.  Here is the latest one for a component I worked on the other day: 

https://github.com/acl-services/paprika/blob/master/packages/CollapsibleChecklists/CHANGELOG.md#108

**Comment by nahumzs** [comment]
ohh yeah this was the initiator for changelogs :D
