### ISSUE TITLE
Side Panel Design Tweaks

### ISSUE THREAD

**Issue by johnpeele** [acl-services/paprika#298]
### Design tweaks

**Default Header**
1. Use the `<Heading>` component for the headings, but keep the font-weight `700` for both the Default and Compact variations
2. Make the close button `size={ShirtSizes.MEDIUM}`
3. Close button icon should be white

**Default Footer**
1. Use `size="large"` for buttons 

**Compact Header**
1. Reduce height from `56px` to `48px`
2. You could make the `padding: 12px 16px` instead of `padding: 0 16px` but it should work either way
3. Make the close button `size={ShirtSizes.SMALL}`

**Compact Footer**
1. Use `size="large"` for buttons

🗒️**Actually, all footers should be `72px` tall and use `size="large"` buttons**

**Child Panel offsets**
1. Default size = `32px` top and bottom
2. Compact size = `24px` top and bottom

**Comment by oscarkwan** [comment]
hey @johnpeele, the footer's buttons are flexible and it is really up to the consumer to put the buttons as large. Not sure if we can enforce it
