### ISSUE TITLE
Button component does not show that its pressed when clicking "Enter"

### ISSUE THREAD

**Issue by oscarkwan** [acl-services/paprika#299]
# Bug Report
## Expected behavior
Press space or use mouse to click the button, it shows a subtle indent in the button to show user feedback.

## Current behavior
When clicking enter, it does not show any feedback to the user

**Comment by alexzherdev** [comment]
@oscarkwan normal html buttons are not `:active` when you press enter, so why should ours be?

**Comment by oscarkwan** [comment]
Good point, let me verify with designers
