### ISSUE TITLE
Form element show warnings for a div/span child

### ISSUE THREAD

**Issue by AndreyChernykh** [acl-services/paprika#302]
# Bug Report
## Prerequisites

*Please fill in as much detail as possible below*

## Expected behavior

Expected no warnings. 

## Current behavior

`backend.js:6 Warning: React does not recognize the `hasError` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `haserror` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

`backend.js:6 Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

`Warning: React does not recognize the `isReadOnly` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isreadonly` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

## Screenshots / Gifs / Codepens

```js
<FormElement label={label}>
  <span>{value}</span>
</FormElement>
```

![image](https://user-images.githubusercontent.com/457894/69389945-62bc2280-0c82-11ea-9502-1f06bc35603e.png)

## Additional context

This pattern is commonly used in forms to display read-only values.

**Comment by jamiek-acl** [comment]
Spoke with Andrey and believe this is outdated.  The only way to get that console warning is to do this:
```
<FormElement>
  <span hasError isDisabled isReadOnly>
    Hello World
  </span>
</FormElement>
```
in which case the consumer should just not include those props on the `span`.
