### ISSUE TITLE
Tabs component tabs keyboard focus issues

### ISSUE THREAD

**Issue by tristanjasper** [acl-services/paprika#310]
# Bug Report

As recommended in https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls

1. Tabs should still be focusable even when disabled (same as menu items in a menu or options in a listbox)

2. Currently using arrow keys changes the focus to the next tab, however pressing shift tab sets focus to the first tab. Pressing the right arrow after this doesn't then focus the tab next to it as expected.

## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a bug report.
- [ ] I checked to make sure that this bug has not already been filed
- [ ] I reproduced the bug in the latest version of paprika
- [ ] Please label as, low / medium / high priority

*Please fill in as much detail as possible below*

## Expected behavior
*Please describe the behavior you are expecting to happen.*

## Current behavior
*What is the current behavior?*

## Screenshots / Gifs / Codepens

![tabs-keyboard-focus](https://user-images.githubusercontent.com/4040102/69683004-287ac880-1068-11ea-9e32-8762cd35d72b.gif)

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by mikrotron** [comment]
I believe this functionality is correct in the `<ButtonGroup>` and it might make the most sense to extract to logic to a custom hook that can be shared.
