### ISSUE TITLE
A disabled <Button.Link>

### ISSUE THREAD

**Issue by alexzherdev** [acl-services/paprika#368]
# Feature request
## Is your feature request related to a problem?
`<Button.Link>` allows rendering a link that looks like a button. However, it does not allow for a faithful reproduction of a disabled button.

## Describe the solution you'd like
You can already use `<Button.Link isDisabled />` but it doesn't have a disabled cursor and it still looks like you can click the thing. When properly implemented, this would function and look the same as a normal disabled button.

## Describe alternatives you've considered
I'm currently using a workaround which is fairly verbose as you can see:
```jsx
        {isEnabled ? (
          <Button.Link kind="primary" href={href}>
            Label
          </Button.Link>
        ) : (
          <Button kind="primary" isDisabled>
            Label
          </Button>
        )}
```

## Additional context
The use case right now is a popup that waits for a download to be ready, during which time the download button/link is disabled. When the download is ready, the link becomes enabled with the href leading to the download.

![linkbutton](https://user-images.githubusercontent.com/93752/71605357-1257a080-2b1d-11ea-9a7c-17d12a8975ce.gif)

**Comment by mikrotron** [comment]
Resolved by:
https://github.com/acl-services/paprika/pull/565
