### ISSUE TITLE
<Modal> and <form> do not mix

### ISSUE THREAD

**Issue by alexzherdev** [acl-services/paprika#369]
# Bug Report
## Expected behavior
I need to implement a very common use case: a form in a modal (see example below). I'm expecting to be able to put my form fields inside `<Modal.Content>` and have a "submit" type button in `<Modal.Footer>`.

## Current behavior
This does not seem to be possible.
Since the submit button has to be a descendant of the form element, I have two options:

a)
```jsx
<form>
  <Modal>
    <Modal.Content><input type="text" /></Modal.Content>
    <Modal.Footer><Button type="submit"></Button></Modal.Footer>
  </Modal>
</form>
```
^ this doesn't work because the modal is rendered in a portal. In the resulting DOM, the form element is empty.

b)
```jsx
<Modal>
  <form>
    <Modal.Content><input type="text" /></Modal.Content>
    <Modal.Footer><Button type="submit"></Button></Modal.Footer>
  </form>
</Modal>
```
^ this doesn't work because `<Modal>` uses `extractChildren` and expects its subcomponents to be its direct children.
## Screenshots / Gifs / Codepens
![image](https://user-images.githubusercontent.com/93752/71609620-c0277700-2b3e-11ea-8310-1e30b29765d5.png)

## Additional context
Ok, I lied. In my particular case the form is AJAX-y, so technically the button doesn't _have_ to be inside the form element. **However**, I would argue that forms in modals are such a common case, we should definitely support a regular, non-AJAX HTML form.
Let's make sure we consider common scenarios like that when designing our APIs; I believe this was possible in ACL UI modals. We wanted to opt for a different composition model in Paprika but failed to notice it prohibits cases like this one.
(Also here's your regular plug for always trying to opt for context-based composition first—which would have made option b) possible. I believe switching from `extractChildren` to context is still possible for our modal, but would require changing the Overlay API. LMK if you need details)

**Comment by alexzherdev** [comment]
1) Actually, this seems to be a real nuisance for AJAX forms as well.
If I want my form fields to be controlled, I'm basically forced to stuff all my form related code into the same component that renders the modal—so that the submit handler can access form state. I can't seem to find any way to break this apart into multiple components.
```jsx
const [value, setValue] = React.useState('');
function handleSubmit() {
  // submit `value` to the server
}
return (
  <Modal>
    <Modal.Content>
      <form>
        <input value={value} onChange={e => setValue(e.target.value)} />
      </form>
    </Modal.Content>
    <Modal.Footer>
      <Button onClick={handleSubmit} />
    </Modal.Footer>
  </Modal>
);
```

I tried a workaround where the form is extracted and I put an `onSubmit` handler on it; then in the modal, I get the form element by ID and try to invoke that handler. But this doesn't work because the button isn't an actual "submit" button (it can't be; as mentioned in the OP, the button isn't actually nested inside the form).

2) Accessibility also suffers. The native behaviour of submitting the form when Enter is pressed in a field is only enabled when there is a submit button properly nested in the form.

**Comment by nahumzs** [comment]
Yes is true that we failed in handling this case of scenario, but worth noting that this issue is more prominent as well because of the need for us of using a portal.

I agree also that we should be using more a context base first approach and then go for the extractChildren logic when/if make sense at all. 

About no being able to extract the logic in a separate file you can simply use Fragments https://codesandbox.io/s/lively-moon-qel4z
So actually it's possible to split logic into different files. 

I will try to fix this today/tomorrow. Can you slack me what it's the initiative that you are working so I can file a ticket?

**Comment by nahumzs** [comment]
The previous commit let the consumer convert the `div` container of the Modal into a `form element` via the `as={}` prop provided by styled-components, this is not the ideal solution, but a next PR should come fixing the full issue of adding a context to share state and let the consumer render a modal like:

```js
<Modal>
  <form>
    <Modal.Content></Modal.Content>
    <Modal.Footer></Modal.Footer>
  </form>
</Modal>
```

**Comment by tristanjasper** [comment]
https://github.com/acl-services/paprika/pull/921 has added context to the modal, however this doesn't completely solve the issue of the submit button. We still need to support `isSemantic` false prop (for consuming applications compatibility)

https://github.com/acl-services/paprika/blob/master/packages/Button/src/Button.js#L46

**Comment by tristanjasper** [comment]
Closing this ticket now as the primary issue here has been fixed. 

https://github.com/acl-services/paprika/issues/369#issuecomment-777843798 is still a relevant issue but at this time we still need to support `isSemantic={false}` on Buttons for consuming apps
