### ISSUE TITLE
<Input>: onChange not required if uncontrolled

### ISSUE THREAD

**Issue by alexzherdev** [acl-services/paprika#374]
# Bug Report
## Expected behavior
I'm expecting to be able to use `<Input>` uncontrolled in its simplest form:
```jsx
<Input defaultValue="foo" />
```

## Current behavior
I can do this, but also constantly getting a propType error. We should not be requiring `onChange` to be present.

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*
![image](https://user-images.githubusercontent.com/93752/71702197-eccbd080-2d82-11ea-8599-c06242298498.png)

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by allison-c** [comment]
This one is fixed in https://github.com/acl-services/paprika/pull/524
