### ISSUE TITLE
Plain text breaks <FormElement>

### ISSUE THREAD

**Issue by alexzherdev** [acl-services/paprika#376]
# Bug Report
## Expected behavior
Although pretty rare, I'm expecting to be able to put plain text inside `<FormElement>`.

## Current behavior
The component breaks completely with the error

> Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

This is likely because we're indiscriminately running `cloneElement` on every direct child. https://github.com/acl-services/paprika/blob/1f5f23033036ead57908dad94d3d1b4b76e41351/packages/FormElement/src/FormElement.js#L167
https://reactjs.org/docs/react-api.html#isvalidelement might be useful here.

## Screenshots / Gifs / Codepens
```jsx
<FormElement label="label">
  blah
  <Input />
</FormElement>
```

## Additional context
This is not blocking anything right now, so low priority.

**Comment by mikrotron** [comment]
This was resolved in the refactor of `<FormElement>` 
https://github.com/acl-services/paprika/pull/774
