### ISSUE TITLE
Can not put <ListBox.Option> under nested <React.Fragment>

### ISSUE THREAD

**Issue by oscarkwan** [acl-services/paprika#382]
# Bug Report
## Expected behavior
- To be able to compose the component in a more flexible way, it would be great so that <ListBox.Option> can be nested under multiple fragments

## Current behavior
https://codesandbox.io/s/exceed-state-6jb0k

**Comment by nahumzs** [comment]
won't do this at the moment, there are multiple alternatives and is only affecting the style of coding the component. In the future, if more devs require this specific functionality for specific feature requirements apart for style syntax I will address the requirement.
