### ISSUE TITLE
Modals API inconsistency 

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#390]
# Bug Report

This is not a bug per se but affects consistency across our API, Modals, SidePanel and Takeover have subtle API variations when all of them should behave exactly the same:

## FocusLock

The correct API use for FocusLock is the one on the SidePanel.

```
<SidePanel>
   <SidePanel.FocusLock disabled />
</SidePanel>
```
[codesandbox](https://codesandbox.io/s/paprikasidepanel-tv0qo)

The Modal need a little more convoluted way to achieve the same:

**Modal**

```
<Modal>
   <Modal.Overlay extractedFocusLockOptions={{ disabled: true }} />
</Modal>
``` 

[codesandbox](https://codesandbox.io/s/paprikamodal-hpp38)

And finally the `<Takeover />` is not exposing the FocusLock at all.

## Component `<Content />`

There is an inconsistency with the SidePanel lacking a `<SidePanel.Content />` subcomponent.  Takeover and Modal accept a `<Modal.Content />` or `<Takeover.Content />`  subcomponent, the SidePanel shouldn't impose or modify the padding in their container div that is the responsibility for the subcomponent Content.

Fixing this subtle difference will help us to have a more consistent API which is easier to reuse over and over reducing cognitive load on our consumers. 

As well as fixing the FocusLock will allow us to use code sandbox without stealing the focus from the IDE and prevent it from coding on it. 

While on it would be good to update the Readme file for these components.

**Comment by mikrotron** [comment]
Resolved by https://github.com/acl-services/paprika/pull/439
