### ISSUE TITLE
<Listbox> trigger onClear should also trigger onChange

### ISSUE THREAD

**Issue by oscarkwan** [acl-services/paprika#396]
# Bug Report
## Prerequisites
- [ ] I checked to make sure that this bug has not already been filed
- [x] I reproduced the bug in the latest version of paprika
- [ ] Please label as, low / medium / high priority

## Expected behavior
- When i click the X button inside the Listbox trigger. I want it to fire the same handler as when you select an option. This is because in how i am using it, i need to provide the consumer that the value is set to empty when the x button is clicked. 

## Current behavior
- In the current behaviour, the onChange handler is not fired when the trigger x button is clicked.

## Codesandbox
https://codesandbox.io/s/listbox-clear-button-issue-q4ue3

**Comment by nahumzs** [comment]
did you try using `<ListBox.Trigger onClickClear={} />` is that enough?

```js
        <Listbox.Trigger onClickClear={handleClickClear} />
```

https://codesandbox.io/s/listbox-clear-button-issue-p3tnu

**Comment by nahumzs** [comment]
@oscarkwan do this one still should be open?

**Comment by oscarkwan** [comment]
lets close for now
