### ISSUE TITLE
Fix the focusing outline inside <Modal>

### ISSUE THREAD

**Issue by allison-c** [acl-services/paprika#400]
# Bug Report

## Expected behavior
*Please describe the behavior you are expecting to happen.*

## Current behavior
When the modal header or the body is having focus, the outline looks like a bug. 

## Screenshots / Gifs / Codepens
![image](https://user-images.githubusercontent.com/38733362/72936681-8a7c4500-3d1c-11ea-9841-ae978c951d7a.png)

## Additional context
Either the header or the body is having focus, and the outline looks like a bug. We can remove the outline or maybe apply the standard focused outline.

**Comment by alexzherdev** [comment]
Already closed as https://github.com/acl-services/paprika/issues/365

**Comment by allison-c** [comment]
> Already closed as #365

Oh but it's still having the issue on master branch, maybe not being published yet, I'll close then
