### ISSUE TITLE
Modals API Inconsistency - Part 2

### ISSUE THREAD

**Issue by mikrotron** [acl-services/paprika#442]
### Problem
Modal components `<Modal>` and `<Takeover>` do not have generic dialog props that the `<SidePanel>` does, namely `zIndex` and `a11yText`.  

### Solution
Add those two props to both  `<Modal>` and `<Takeover>`.

**Comment by nahumzs** [comment]
does the following has been addressed?

> There is an inconsistency with the SidePanel lacking a <SidePanel.Content /> subcomponent. Takeover and Modal accept a <Modal.Content /> or <Takeover.Content /> subcomponent, the SidePanel shouldn't impose or modify the padding in their container div that is the responsibility for the subcomponent Content.

**Comment by mikrotron** [comment]
> does the following has been addressed?
> 
> > There is an inconsistency with the SidePanel lacking a <SidePanel.Content /> subcomponent. Takeover and Modal accept a <Modal.Content /> or <Takeover.Content /> subcomponent, the SidePanel shouldn't impose or modify the padding in their container div that is the responsibility for the subcomponent Content.

No, but I've moved that to a new issue (https://github.com/acl-services/paprika/issues/495) and will close this one now.
