### ISSUE TITLE
DataGrid fails throws is Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#450]
# Bug Report
if you set and an empty array for the data prop using the DataGrid the following console error occurs. 

`The error is Uncaught TypeError: Cannot read property 'addEventListener' of null`

**Comment by oscarkwan** [comment]
Plus one

**Comment by nahumzs** [comment]
this has been fixed while doing the performance updates for datagrid.
