### ISSUE TITLE
Modal of CKEditor in SidePanel cant get focus

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#453]
# Bug Report
## Current behavior
When a @paprika/SidePanel contains a CKEditor, if you do something in CKEditor that opens one of its modals (e.g. insert a table), the SidePanel and CKEditor modal fight for focus.  The SidePanel (which uses `react-focus-lock`) gives up the fight (https://www.npmjs.com/package/react-focus-lock#warning), and CKEditor takes it back, but focuses on the parent iframe -- not the modal.  This makes it impossible to change any of the values in the modal.

[EDIT]

---

## Workaround

The solution/workaround is to tell the SidePanel to not take back focus when it goes to a child of a CKEditor modal. You do that by including the `<SidePanel.FocusLock>` child component, with the `whiteList` prop:

    <SidePanel>
      <SidePanel.FocusLock
          whiteList={focusedElement => {
            const ckEditorModals = document.querySelectorAll('.cke_dialog');
            let focusedElementIsChildOfCkEditorModal = false;

            for (let i = 0; i < ckEditorModals.length; i++) {
              if (ckEditorModals[i].contains(focusedElement)) {
                focusedElementIsChildOfCkEditorModal = true;
              }
            }

            if (focusedElementIsChildOfCkEditorModal) {
              return false; // focus on this element
            }

            return true; // dont focus on this element - keep focus in lock
          }}
        />
      ...
    </SidePanel>

Note: if you use `.contains` like I did above, and want it to work in IE11, you will need to polyfill it.
Note: don't use `document.querySelectorAll('...').forEach()` -> IE 11 doesn't support `NodeList.forEach`.

## Additional context
You can read about `whiteList` here: https://www.npmjs.com/package/react-focus-lock

![Screen Shot 2020-03-11 at 3 24 09 PM](https://user-images.githubusercontent.com/23224777/76469862-66e48b00-63ac-11ea-857f-3d0cf149d5f5.png)

**Comment by nahumzs** [comment]
A workaround for this specific scenario has been provided on the description of the issue, closing this issue.

**Comment by nahumzs** [comment]
Can you add this to the readme file for the SidePanel, takeover and modal? I think we should have a section for caveats or something else to warn developers about these issues. what do you think? @jamiek-acl

**Comment by jamiek-acl** [comment]
@nahumzs https://github.com/acl-services/paprika/pull/482

**Comment by nahumzs** [comment]
closing this we have added it to the read me file
