### ISSUE TITLE
L10n version as peer dependency need to be updated

### ISSUE THREAD

**Issue by allison-c** [acl-services/paprika#463]
# Bug Report

## Current behavior
You might experience some weird translation issue happens on some paprika component, like:

- The component is partially translated
- The component is not translated at all even you already used `@paprika/l10n` to wrap it correctly
- The translation results are outdated, for example, it's different than the results on paprika master demo site

Please try to upgrade `@paprika/l10n` in your app first, which will likely solve the issues above.

Meanwhile, we need to review the peer dependency version of `@paprika/l10n` in all paprika components, also keep them updated all the time

## Screenshots / Gifs / Codepens

For example, you might see this with date picker:

![image](https://user-images.githubusercontent.com/38733362/77355770-4a2c4980-6d02-11ea-98e6-5d0761da897d.png)

All the dates, `Apply` and `Cancel` button are translated, but `Month` and `Year` are not.

### Translation sources of Date picker

Date picker component has 2 sources of translation.

- Using moment localization source to translate the date(e.g. March, Monday, Feb ...)
- Using paprika l10 to translate other UI parts (e.g. Apply, Cancel, Year, Month ...)

That's why when you use the Date picker component you have to not only wrap your app in a `<L10n />` component but also run `moment.locale(your_current_locale)` when the app initiated.

### Peer dependency issue

When we add a new component into paprika master, we add `L10n` as a peer dependency for the new component, but at that time we usually don't have all the localization files yet. One or two weeks after, l10n team will add the localization files, but we forget to update the version of `L10n` in the peer dependency. Consumers might install the old version of `L10n`, and that version doesn't have all the translations, but there's no error shows up.

**Comment by nahumzs** [comment]
This is a great explanation about the issues with `L10n` component, would you mind to add these notes into the L10n's readme file? We should add a section maybe named caveats, so people are aware of them and how to fix it. 🙏 @allison-c

**Comment by allison-c** [comment]
Resolved by https://github.com/acl-services/paprika/pull/886
