### ISSUE TITLE
Takeover.Overlay propType warnings

### ISSUE THREAD

**Issue by mikrotron** [acl-services/paprika#470]
## Description
Console warnings are observed when `isOpen` prop is omitted from `<Takeover.Overlay>`, even though it is provided on the parent `<Takeover>` component.

## Detail
- The `defaultProps` from the `@paprika/overlay` are being applied directly to the `<Takeover.Overlay>` here:
https://github.com/acl-services/paprika/blob/master/packages/Takeover/src/components/Overlay.js#L3
- This is inappropriate since a bunch of those props are provided by the `<Takeover>`:
https://github.com/acl-services/paprika/blob/master/packages/Takeover/src/Takeover.js#L56-L64

**Comment by nahumzs** [comment]
^ do this one was solved in your previous PR @mikrotron can you close it?
