### ISSUE TITLE
Need collaborator to create a @types/paprika package for typescript

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#471]
# Feature request

Paprika will be used inside of typescript env. Right to circumvent the lack of types definition for our library you can add a `global.d.ts` file with a content like:

```ts
declare module "@paprika/button";
declare module "@paprika/form-element";
declare module "@paprika/heading";
```

But in order to improve our developer's experience, we should have a package with all these definitions.

**Comment by nahumzs** [comment]
cc @jamiek-acl this is the issue for typescript types.

**Comment by jamiek-acl** [comment]
See https://github.com/acl-services/wasabicons/issues/16#issuecomment-631641065
