### ISSUE TITLE
Tabs [feature] - Adding capability to programatically set the active tab

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#483]
## Describe the solution you'd like
The Tabs components should provide a way to select a tab programmatically.

**Comment by nahumzs** [comment]
Maybe we can do this via https://reactjs.org/docs/hooks-reference.html#useimperativehandle

**Comment by jamiek-acl** [comment]
Jira ticket: https://aclgrc.atlassian.net/browse/UXD-786
