### ISSUE TITLE
ListBoxBrowser - show default selected option

### ISSUE THREAD

**Issue by robyn3choi** [acl-services/paprika#484]
# Feature request
## Is your feature request related to a problem?
This is only relevant when `isMulti={false}` and there is no `<ListBoxBrowser.OptionsSelected />`. When an option is default selected (using `defaultSelectedOptions`) and is not at root level, the user can't see that there is a default selected option unless they navigate to the level of that option.

## Describe the solution you'd like
If there's a default selected option that is not at root level, the ListBoxBrowser should load showing the level that contains the default option, so that it's clear to the user that there is a default option.

## Describe alternatives you've considered
*A clear and concise description of any alternative solutions or features you've considered.*

## Additional context
In this gif, there is a default selected option but you can't see it unless you navigate to it.
![listboxbrowser](https://user-images.githubusercontent.com/9066587/79286996-38f4d980-7e77-11ea-823b-7dea7f47dd0e.gif)

**Comment by nahumzs** [comment]
I might be wrong, but isn't in this specific case you should implement the `defaultSelectedView` to show the selected view? 

In this example look how Black Cat its selected https://paprika.highbond.com/?path=/story/listboxbrowser-multi--has-view-default-selected

^ you might need to do the same isn't it?

<img width="1008" alt="Screen Shot 2020-04-14 at 6 56 11 PM" src="https://user-images.githubusercontent.com/19418590/79290693-aa398a00-7e81-11ea-958d-8cb9fc886a2b.png">

`Story:`
https://github.com/acl-services/paprika/blob/27a0d359f68ec014f8af4acd3e1a6653b8106c31/packages/ListBoxBrowser/stories/ListBoxBrowser.multiple.stories.js#L85

`The prop on the code:`
https://github.com/acl-services/paprika/blob/master/packages/ListBoxBrowser/src/ListBoxBrowser.js#L97

**Comment by robyn3choi** [comment]
You're right, I didn't know that's what `defaultSelectedView` did. I was able to successfully display the options view that contained the default selected option by setting these props:
```
defaultSelectedOptions={option => option.label === myDefaultOptionLabel}
defaultSelectedView={option => option.options.some(o => o.attributes.label === myDefaultOptionLabel)}
```
It works but it still seems like kind of a roundabout way to display a default selected option in the correct view. Thanks for the tip!

**Comment by nahumzs** [comment]
The same technique is used for navigating across the entire tree from anywhere this makes it possible to render the `crumb navbar` and be able to click and switch the view. Same for displaying the selected values and be able to jump to the exact view.
