### ISSUE TITLE
ListBox - Expose trigger focus api for formElement

### ISSUE THREAD

**Issue by tristanjasper** [acl-services/paprika#544]
Expose trigger focus api for formElement and replicate the ButtonGroup approach with FormElement (that is merged in https://github.com/acl-services/paprika/pull/536 ) as an example of that label focus integration can look.

**Comment by nahumzs** [comment]
Seems that we should figure out how to expose the ability to focus on the listbox but from the formElement? @mikrotron do you have more context for this issue?

**Comment by mikrotron** [comment]
I haven't really used the ListBox, but I think the suggestion is to make focussing the ListBox.Trigger as simple as this:
https://github.com/acl-services/paprika/blob/master/packages/ButtonGroup/stories/examples/Sandbox.js#L29-L31

How is it achieved now?

**Comment by nahumzs** [comment]
<ListBox ref={refListBox} />

`refListBox.focus` :P 

thats it.

**Comment by mikrotron** [comment]
In that case, we'll need to ask @tristanjasper what his intention was here.

**Comment by tristanjasper** [comment]
Unsure, looks like this isn't an issue now.
