### ISSUE TITLE
ActionBar - Sort by boolean is backwards

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#555]
Sorting data based on a boolean row sorts in the opposite direction than what you ask for.
sorting by other data types works fine.

![Screen Shot 2020-06-05 at 1 55 16 PM](https://user-images.githubusercontent.com/23224777/84050974-561fc300-a963-11ea-9386-fad0596e8f1b.png)

**Comment by allison-c** [comment]
Resolved. https://github.com/acl-services/paprika/commit/87d78ec0a3f9c0ed486b351c40968af8db6026d9#diff-cd6fb85b9e84fb755e56cbd881b408f59ace7580935793ae232f419c057ef03e
