### ISSUE TITLE
ActionBar - common naming patterns

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#558]
In ActionBar's useFilter hook, please make this function name follow Paprika's pattern:

onFilterChange -> onChangeFilter

Maybe these Sort names are more consistent with the rest of ActionBar? Though not as important
onDeleteField -> onDeleteSort
onChangeField -> onChangeSort

**Comment by allison-c** [comment]
Fixed in https://github.com/acl-services/paprika/pull/560
