### ISSUE TITLE
Listbox - onchange index includes dividers as items and doesn't include any detail on which group selected item is from.

### ISSUE THREAD

**Issue by tristanjasper** [acl-services/paprika#658]
... this then makes it impossible to know the correct item index when working with groups

# Bug Report
## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a bug report.
- [ ] I checked to make sure that this bug has not already been filed
- [ ] I reproduced the bug in the latest version of paprika
- [ ] Please label as, low / medium / high priority

*Please fill in as much detail as possible below*

## Expected behavior
*Please describe the behavior you are expecting to happen.*

## Current behavior
*What is the current behavior?*

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by nahumzs** [comment]
The Listbox doesn't have a concepts of groups only concept about indexes, even if the dividers are part of those indexes that doesn't prevent you from knowing which item has been selected:

```js
function handleChange(index, options) {
  // depending if it's isMultipe or not index can be an integer or an array of integer which later you can 
  // use to decide which options was selected

  // in case the use select index 1 you can do
  console.log(options[index]) // and have access to the option one 
}

<ListBox onChange={handleChange}>
  <ListBox.Divider>My first divider</ListBox.Divider>
  <ListBox.Option>a1</ListBox.Option>
  <ListBox.Option>b1</ListBox.Option>
  <ListBox.Option>c1</ListBox.Option>
  <ListBox.Divider>My Second divider</ListBox.Divider>
  <ListBox.Option>a2</ListBox.Option>
  <ListBox.Option>b2</ListBox.Option>
  <ListBox.Option>c2</ListBox.Option>
</ListBox>
```

So you can see in the previous example that doesn't matter if the dividers are part or not of the options parameter you will always will have the correct index to access the correct options.

if what you want to get in what group is part a individual option then you can do this from the consumer part using the `value` prop on `<ListBox.Options value="" />`

```js
  function handleChange(index, options) {
     // depending if it's isMultipe or not index can be an integer or an array of integer which later you can 
     console.log(options[index].value) // this should print GroupA or GroupB depending the selection

     // NOTE the value can be anything from number, string to an object. 
  }

<ListBox onChange={handleChange}>
  <ListBox.Divider>My first divider</ListBox.Divider>
  <ListBox.Option value="groupA">a1</ListBox.Option>
  <ListBox.Option value="groupA">b1</ListBox.Option>
  <ListBox.Option value="groupA">c1</ListBox.Option>
  <ListBox.Divider>My Second divider</ListBox.Divider>
  <ListBox.Option value="groupB">a2</ListBox.Option>
  <ListBox.Option value="groupB">b2</ListBox.Option>
  <ListBox.Option value="groupB">c2</ListBox.Option>
</ListBox>
```
