### ISSUE TITLE
NanoId polyfill for ie11 not working

### ISSUE THREAD

**Issue by tristanjasper** [acl-services/paprika#734]
# Bug Report

If we use nanoId v3 and upwards there is an Ie 11 syntax error. 
We need to investigate why the polyfill solution did not work at the paprika level or at application level.

Investigative pr: https://github.com/acl-services/paprika/pull/728
Related PR:
https://github.com/acl-services/paprika/issues/724

## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before submitting a bug report.
- [x] I checked to make sure that this bug has not already been filed
- [ ] I reproduced the bug in the latest version of paprika
- [ ] Please label as, low / medium / high priority

*Please fill in as much detail as possible below*

## Expected behavior
*Please describe the behavior you are expecting to happen.*

## Current behavior
*What is the current behavior?*

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by tristanjasper** [comment]
Closing the PR as not currently being worked on https://github.com/acl-services/paprika/pull/728

**Comment by nahumzs** [comment]
bringing back uuid instead of nanoid, to ease test on our developers and avoid issues with IE11
