### ISSUE TITLE
`readme`s not appearing on npm

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#76]
# Bug Report

Check out the L10n component on npmjs.org: https://www.npmjs.com/package/@paprika/l10n
It says `"Unable to find a readme for @paprika/l10n@0.1.0"

But there is a readme: 
https://github.com/acl-services/paprika/blob/master/packages/L10n/src/readme.md

**Comment by alexzherdev** [comment]
Here's what published to npm: https://unpkg.com/@paprika/l10n@0.1.0/

The readme is in `lib`, should be in root - we should move it up from `src`. Also conventionally it's `README.md`.

**Comment by jamiek-acl** [comment]
Should be fixed by the merge above, but don't close this issue until paprika has been deployed and sure the problem is fixed.

**Comment by nahumzs** [comment]
readme is available now https://www.npmjs.com/package/@paprika/l10n
