### ISSUE TITLE
ListBox vs Listbox

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#775]
Small thing, but inconsistent and I ran into it when trying to import it.  In the repo the component is named `ListBox`. The capital `B` implies it is a second word (as that is how the other components are named), so you should include it with a hyphen like this:

```
import xxx from '@paprika/list-box;
```

But that actually doesn't work as in NPM it is one word: https://www.npmjs.com/package/@paprika/listbox, so you import it like this:

```
import xxx from '@paprika/listbox;
```

Probably worse to replace it in NPM, so instead I say just change the directories/files to be called `Listbox` instead of `ListBox`.

**Comment by nahumzs** [comment]
we can fix this once we roll all our component to version 1.0.0, this and dropdownmenu can be deprecated and set them up properly. This in particular was an issue I run because I thought listbox was 1 work in English, ESL Issues :/ sorry.

cc @mikrotron

**Comment by jamiek-acl** [comment]
Handled here: https://github.com/acl-services/paprika/pull/779
