### ISSUE TITLE
DataGrid `lazy` example

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#782]
# Bug Report
This story: https://paprika.highbond.com/?path=/story/table-datagrid-examples--lazy hits an external API.  Some of the Cypress tests use it.  I ran into a problem where the API was down, so cypress tests were failing and I couldn't merge my PR.  Update this story to not use an external API.

**Comment by jamiek-acl** [comment]
The `Search` component now also hits an external API (the Marvel API), so it is susceptible to this and should be updated as well.

**Comment by allison-c** [comment]
We had to disable the cypress tests using DataGrid lazy example to unblock the pre-release build. https://github.com/acl-services/paprika/pull/872/commits/2af4abc1ba461c4d2b579021051c3206f62b6939

Definitely better to use a fake server.

**Comment by jamiek-acl** [comment]
Done here: https://github.com/acl-services/paprika/pull/883
