### ISSUE TITLE
RFC <SidePanel />

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#79]
# New Component
## Prerequisites
**This is just a checklist, please delete this section after**
Please answer the following questions for yourself before suggesting a new component.
- [x] I checked to make sure that this new component has not already been suggested
- [x] Are there any components in our repo that can be reused?
- [x] Please label as, low / medium / high priority

*Please fill in as much detail as possible below*
From #4 issue 

## Overview
This RFC addressed the <SidePanel /> refactoring. 

[Figma](https://www.figma.com/file/dGl8bgX4FF81ixllzAjRFzDO/Sidepanel?node-id=0%3A1)

We have reduced the use cases for the sidepanel in three basic cases and two different location for the SidePanel (left and right).

Extra cases is a SidePanel inside of a SidePanel also could be seen as two sidepanel one next to the other one. 

## Visual representation and Propose API:

<img width="356" alt="Screen Shot 2019-05-15 at 3 18 59 PM" src="https://user-images.githubusercontent.com/19418590/57813432-e837a680-7724-11e9-8022-45ab62022bb2.png">

#### description

The most common SidePanel. Takeover the entire screen without letting the user to interact with the body content. Might have or not overlay and the body content might or might not be scrollable

#### API

```js
<SidePanel isOpen={bool} onClose={fn}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Footer />
</SidePanel>
```

---

<img width="658" alt="Screen Shot 2019-05-15 at 3 19 13 PM" src="https://user-images.githubusercontent.com/19418590/57813420-e4a41f80-7724-11e9-8c94-34cd294465bc.png">

The second most common option, unlinke the (A) SidePanel option, this one has an top offset which allows it to have a different height and be more integrated with the Interface. This SidePanel let the user interact with the entire UI. 

#### API

```js
<SidePanel isOpen={bool} onClose={fn} offset={number}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Footer />
</SidePanel>
```

> The offset will indicate how much space the sidepanel should include from the top. The offset should be passed from the consumer is their responsability. 

---
 
<img width="343" alt="Screen Shot 2019-05-15 at 3 19 18 PM" src="https://user-images.githubusercontent.com/19418590/57813421-e4a41f80-7724-11e9-9cb9-a50704ce4451.png">

Exactly as the SidePanel (B) except that includes a second SidePanel letting the consumer to have another area where "Extra" data can be displayed.

#### API

```js
<SidePanel isOpen={bool} onClose={fn} offset={number}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Footer />
</SidePanel>
```

We could inspect the children and detect the number or `SidePanel.Content` and then nested the content depending of the position of the content.

*- or -*

```js
<SidePanel isOpen={bool} onClose={fn} offsetY={number}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Footer />
</SidePanel>
<SidePanel isOpen={bool} onClose={fn} offset={number} offsetX={number}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Footer />
</SidePanel>
```

We could render two sidepanel one each of the other one and just affect the offset position.

*- or -*

```js
<SidePanel isOpen={bool} onClose={fn} offsetY={number}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.SubContent>[node]</SidePanel.SubContent>
   <SidePanel.Footer />
</SidePanel>
```

Create a specific subcomponent to deal with the second sidepanel

*Note* I'm `no too` sure about how to deal with this requirement.

---

<img width="465" alt="Screen Shot 2019-05-15 at 3 19 22 PM" src="https://user-images.githubusercontent.com/19418590/57813422-e4a41f80-7724-11e9-9ba4-30162c420873.png">

SidePanels should be able to render from left or right direction.

*Enum:* `Left` || `Right`

```js
<SidePanel slideIn={Enum} isOpen={bool} onClose={fn}>
   <SidePanel.Header>[node]</SidePanel.Header>
   <SidePanel.Content>[node]</SidePanel.Content>
   <SidePanel.Footer />
</SidePanel>
```

## Questions, wondering, not sure. 

- [ ] This component should be Controlled
- [ ] Should not render content when is close
- [ ] Should be agnostic about the width, the consumer should provide the width which can be defined by tokens cc @krismckinnonacl @mikrotron 
- [ ] Shuld we have a `<Footer />` popover, sidepanel and multiselect ? All of them migth benefit for having the same behaviour. cc @krismckinnonacl @johnpeele @jayde-acl 
- [ ] not sure about the API for the second sidepanel content. 

## A11y considerations and Responsivenes
Let's discuss only about the layout we can have another ISSUE for those specific topics.

**Comment by AndreyChernykh** [comment]
LGTM

**Comment by nahumzs** [comment]
*note:* Maybe there is not even a need for `SidePanel.Content` I can render whatever is pass in the children. So we would need only `SidePanel.Header`, `SidePanel.Footer`

**Comment by krismckinnonacl** [comment]
@nahumzs I've written a "designer requirement" document that outlines the properties that outline the properties and constraints that I think the side panel should have based on our designs up until now. I've just posted it to the ux design channel for them to review, but I'm posting the link here as well, in case you want to follow along. I'm going to bump it on Monday and then ask for all feedback to be in by 2 days after that. 
(https://aclgrc.atlassian.net/wiki/spaces/UX/pages/604405986/Side+panels+as+a+component+-+design+requirements)

**Comment by nahumzs** [comment]
sorry, @krismckinnonacl had to delete the link you shared, this is an open repo, can we move the information to somewhere else more publicly?

**Comment by nahumzs** [comment]
Yes @KirillKayumov , the Sidepanel shouldn't care about the `[node]` content structure, will render `props.children` always. 

`SidePanel.Header`, `SidePanel.Header`, etc. will use context in case they need it, so they can be at any level.
