### ISSUE TITLE
OverflowMenu focus

### ISSUE THREAD

**Issue by jamiek-acl** [acl-services/paprika#794]
# Bug Report

## Current behavior
1. When you open the `OverflowMenu`, it automatically puts focus on the first item (https://github.com/acl-services/paprika/blob/master/packages/OverflowMenu/src/OverflowMenu.js#L72). Maybe that's fine when using the keyboard, but when using the mouse it is a distraction.  We prevent a similar behaviour using `what-input` on the `@paprika/Button` component and should do the same here: https://paprika.highbond.com/?path=/story/buttons-button-examples--focus).
![focus-mouse](https://user-images.githubusercontent.com/23224777/98750911-ed0a0480-2373-11eb-8afe-629abcde23be.gif)

2. When you try and tab out of an expanded `OverflowMenu` , the focus goes to the next element, but then jumps back to the collapsed `OverflowMenu`. Not cool.
![stealing-focus](https://user-images.githubusercontent.com/23224777/98750511-06f71780-2373-11eb-9b2c-f6269b1f99df.gif)

**Comment by nahumzs** [comment]
> When you try and tab out of an expanded OverflowMenu , the focus goes to the next element, but then jumps back to the collapsed OverflowMenu. Not cool.

Should we check on the `blur` event `event.key === "Tab"` and then just close the menu and ignore the focus part?

**Comment by jamiek-acl** [comment]
https://github.com/acl-services/paprika/pull/804
