### ISSUE TITLE
Addressing Screen Reader for ListBox

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#89]
ListBox is a complex component that needs specific work to make it screen reader compatible, we need an a11y hero, for this task

- [comment 1](https://github.com/acl-services/paprika/pull/77/files/b8c2aa76707e2bbedfb3597d2ecea97b9a233384#discussion_r291405051)
- [comment 2](https://github.com/acl-services/paprika/pull/77#pullrequestreview-246857261)

**Comment by mikrotron** [comment]
Remaining issues have been captured in https://github.com/acl-services/paprika/issues/956
