### ISSUE TITLE
Repository links are not working on npm

### ISSUE THREAD

**Issue by alexzherdev** [acl-services/paprika#91]
# Bug Report

## Expected behavior
Repository links open to an existing page.

## Current behavior
Repository links are incorrect in most, if not all, packages, due to case sensitivity.

## Screenshots / Gifs / Codepens
![image](https://user-images.githubusercontent.com/93752/59532280-1bdd2c00-8e9d-11e9-8552-93ba7b81f54e.png)

## Additional context
Actually, providing a subdirectory within a monorepo doesn't seem to be the correct usage of this field, which is supposed to [refer to the actual cloneable repo](https://docs.npmjs.com/files/package.json#repository). [This example in Storybook](https://github.com/storybookjs/presets/blob/1a4ee04197eb062a7fd56817cd53071253495cdb/packages/preset-typescript/package.json#L11-L15) is the correct one. It would lead to those links just going to the root of the repo for all packages, but we can use the `homepage` field to provide a URL to the appropriate subdirectory.

**Comment by nahumzs** [comment]
has been addressed here https://github.com/acl-services/paprika/pull/364
