### ISSUE TITLE
Strange ListBox behavior

### ISSUE THREAD

**Issue by allison-c** [acl-services/paprika#942]
# Bug Report

## Expected behavior

ListBox should show the selected item in the initial dropdown screen.

## Current behavior

I've created a sandbox example: https://codesandbox.io/s/jolly-ride-jvcp7?file=/src/App.js
Click on the trigger and you cannot find the selected item on the initial dropdown screen, you have to scroll up a little bit to see it.

It was strange because if you try delete the space ` withspace` on line 5, and just use the number as label, it works fine.

## Screenshots / Gifs / Codepens

https://codesandbox.io/s/jolly-ride-jvcp7?file=/src/App.js
![image](https://user-images.githubusercontent.com/38733362/107708329-2bb3a180-6c78-11eb-85e5-7f1a9265f76e.png)

![image](https://user-images.githubusercontent.com/38733362/107708296-1b9bc200-6c78-11eb-939d-247e45ba2f89.png)

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by allison-c** [comment]
Also, it seems like listbox are not working in IE 11, it's a little bit hard to test, because storybook cannot open in IE 11. I just went through some features using listbox, none of them works..

**Comment by nahumzs** [comment]
@allison-c like is not even open? so people are not using all the new features? 🤔

**Comment by allison-c** [comment]
> @allison-c like is not even open? so people are not using all the new features? 🤔

It opens but closes immediately

**Comment by mikrotron** [comment]
This appears to be resolved in `v3.0.0-next.0`

cc @allison-c @nahumzs
