### ISSUE TITLE
Replace componentType for displayName

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#96]
currently, some components use `componentType` as an escape to filter the type of the component while iterating over props.children.

After some reading and suggestions seems that the "correct" way to do this is using 
 "Component.displayName" [see more](https://github.com/facebook/react/issues/4915#issuecomment-335803765)

Help is asked to go and replace any `componentType` in the repo and replace it for `diplayName`

**Comment by alexzherdev** [comment]
I don't think that particular comment is the actual solution for the question though? [This](https://github.com/facebook/react/issues/4915#issuecomment-162730765) looks like one (and the code sample below it).

**Comment by nahumzs** [comment]
Would you prefer to import the instance and compare the type directly? I open to both to me is simpler to just declare displayName than import a component just to be compared. But I will leave this decision to you, I'm good with both.
