### ISSUE TITLE
SidePanel.Footer Flickering while scrolling

### ISSUE THREAD

**Issue by nahumzs** [acl-services/paprika#97]
## Expected behavior

While scrolling the SidePanel the footer should smoothly move and stay stuck at the bottom of the SidePanel

## Current behavior
Every time the user scrolls there is a flickering occurring while repositioning the Footer.

## Screenshots / Gifs / Codepens
*Include media to help illustrate the bug. Gifs help a lot!*

## Additional context
*Please provide any more additional details to illustrate the bug*

**Comment by mikrotron** [comment]
This should be achievable by using a flexbox layout instead of using the `useFooterOffset()` hook.
